name: Notify on Push or Pull Request

on:
  push:
    branches:
      - dev # Trigger on dev branch
  pull_request:
    types: [opened, edited, closed]

jobs:
  notify-push:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Echo Email Username and Password
        run: |
          echo "EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}"
          echo "EMAIL_PASSWORD: ********"  # Password obfuscated for security
          
      - name: Send Email Notification for Push
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          from: ${{ secrets.EMAIL_USERNAME }}
          subject: |
            ${{ github.repository }}: Code Pushed by ${{ github.actor }} in ${{ github.ref_name }} -m "${{ github.event.head_commit.message }}"
          body: |
            A new push has been requested to the repository.
            Repository: ${{ github.repository }}
            Branch: ${{ github.ref_name }}
            Commit: ${{ github.event.head_commit.message }}
            Pushed by: ${{ github.actor }}
          to: 'laleshan7@gmail.com'

  notify-pull:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Echo Email Username and Password
        run: |
          echo "EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}"
          echo "EMAIL_PASSWORD: ********"  # Password obfuscated for security

      - name: Send Email Notification for Pull Request
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          from: ${{ secrets.EMAIL_USERNAME }}
          subject: |
            ${{ github.repository }}: Requested Code Pull by ${{ github.actor }} in ${{ github.base_ref }}
          body: |
            A new pull request has been made to the repository.
            Repository: ${{ github.repository }}
            Base Branch: ${{ github.base_ref }}
            Head Branch: ${{ github.head_ref }}
            Action: ${{ github.event.action }}
            Pulled by: ${{ github.actor }}
          to: 'laleshan7@gmail.com'
